I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/homeMenu.rpy", line 3, in script call
    call screen homeMenuScreen
  File "game/homeMenu.rpy", line 3, in script call
    call screen homeMenuScreen
  File "game/homeMenu.rpy", line 3, in script call
    call screen homeMenuScreen
  File "game/script.rpy", line 557, in script
    $ renpy.end()
  File "game/script.rpy", line 557, in <module>
    $ renpy.end()
AttributeError: module 'renpy.exports' has no attribute 'end'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/homeMenu.rpy", line 3, in script call
    call screen homeMenuScreen
  File "game/homeMenu.rpy", line 3, in script call
    call screen homeMenuScreen
  File "game/homeMenu.rpy", line 3, in script call
    call screen homeMenuScreen
  File "game/script.rpy", line 557, in script
    $ renpy.end()
  File "C:\Users\Andrew\Downloads\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Andrew\Downloads\renpy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 557, in <module>
    $ renpy.end()
AttributeError: module 'renpy.exports' has no attribute 'end'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
marsy 1.01
Mon Dec 11 20:59:20 2023
